DataBase support, Tests added
java-park-mail-ru/KVVArtet-09-2017 pull request #15
Opened 2017-10-17 18:58 UTC by zonder129

2017-10-18 08:38 UTC, isopov commented
1. Давайте версию обновим таки на 2.0.0.M5 (можно либо удалить весь локальный репозиторий, либо по стектрейсу понять какой артефакт загрузился битым и удалить только один битый)
2. Доступ к базе из-под пользователя postgres стоит убрать. Тем более, что в .travis у вас создаётся другой пользователь
3. signOutTest раскоментируйте и почините
4. Для выхода пользователя пользуйтесь `httpSession.invalidate()`, а не просто удаляйте из сессии один аттрибут - и в тесте проверяйте, что сессия полностью инвалидирована.
5. Хранить пароли открытым текстом в памяти еще куда ни шло, но записывать их так в базу нельзя! https://park.mail.ru/blog/topic/view/7197/
6. Вас ничего не смущает в этом коде?
```
        String lastUsername = userService.getUserById(id).getLogin();
        String lastPassword = userService.getUserById(id).getPassword();
```
7. Единственные проверки в ваших тестах, это `.andExpect(status().isOk())` - вы не проверяете ни одного неудачного случая, и не проверяете ничего кроме http-кода - а ведь вы и в теле что-то возвращаете.
8. Кстати, все метод контроллера, вместо `ResponseEntity` могут возвращать `ResponseEntity<String>`
9. Мы же пришли к тому, что `@JsonCreator` в классе может быть только один. И кроме того, ни один из сеттеров, на которые вы его поставили не подходит даже в отдельности для `@JsonCreator` - почитайте (или поспрашивайте) и поковыряйте что это такое до понимания.
10. server.models.ApiResponse.getStatus() - где-то используется?

2017-10-18 08:39 UTC, isopov requested changes
Замечания в комментарии

2017-10-18 22:08 UTC, zonder129 commented
Вопрос за одно - как проверять тело ResponseEntity или хотя бы вовзращаемую им стрингу через Mvc. 
P.S. Раздельные проперти пока не реализовал

2017-10-19 07:59 UTC, isopov commented
1. `spring.flyway.baseline-on-migrate=true` - давайте этим не пользоваться. Либо правьте схему и выбрасывайте и пересоздавайте заново все существующие базы (хуже), либо добавляйте вторую миграцию, где меняйте тип поля пароля
2. Чтобы заработало на Heroku, можно не добавлять еще один application.properties, а изменить существующий как-то так:
```
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/landd}
spring.datasource.username=${DATABASE_LOGIN:landd}
spring.datasource.password=${DATABASE_PASSWORD:landd}
```
3. Доступ к базе из-под пользователя postgres _НАДО_ убрать.
4.  Проверка тела запроса, например так:
```
.andExpect(status().is(400))
.andExpect(MockMvcResultMatchers.content().string(ApiResponse.FIELD_EMPTY.getResponse()))
```
5. Перечитайте первый набор замечаний - куча неисправленных - либо исправляйте, либо говорите явно почему нет (тоже нормально, но прокомментировать надо)

2017-10-19 10:03 UTC, zonder129 commented
Касательно прошлого комментария из исправленного:
1. Исправлено
2. Пока не исправлено, но исправлю.
3. Исправлено.
4. Исправлено.
5. Исправлено.
6. Исправлено.
7. Исправлено.
8. Не очень понял как работать с Mvc в этом плане, доработаю
9. Почитал про Jackson, сделал как понял, по идее сетеры стоят, а creator висит на конструкторе. Что-то не то?
10. Нигде. Убрал и исправил.
11. Не деплою пока не исправлю остальное)

2017-10-22 12:09 UTC, isopov commented
1. Я не понимаю чего вы аннотациями из Jackson на вашем классе добиваетесь. Если написать вот такой тест
```java
public class UserTest {
	private ObjectMapper mapper = new ObjectMapper();

	@Test
	public void testDeserialize() throws Exception {
		assertEquals(new User(1, "foobar", "foo@bar.com", "password"), mapper.readValue(
				"{\"username\":\"foobar\",\"email\":\"foo@bar.com\",\"password\":\"password\",\"id\":1}", User.class));
	}

	@Test
	public void testSerialize() throws Exception {
		assertEquals("{\"username\":\"foobar\",\"email\":\"foo@bar.com\",\"password\":\"password\",\"id\":1}",
				mapper.writeValueAsString(new User(1, "foobar", "foo@bar.com", "password")));
	}
}
```
и удалить их все нафиг, то видно, что всё также и работает. Зачем аннотации?

2. `ResponseEntity<String>` вместо  `ResponseEntity` - к спрингу/джексону это не имеет отношения - это core java - для вашего удобства, чтобы компилятор сделал вам больше проверок. У вас там куча возвратов из одного и того же метода (многие, кстати, считают это антипаттерном) - если вы где-то ошибетесь и напишете `.body(ApiResponse.SIGNUP_VALIDATION_FAILED)` вместо `.body(ApiResponse.SIGNUP_VALIDATION_FAILED.getResponse())` то узнать об этом рискуете только на интеграции с фронтом, а если примете за правило пользоваться параметризованными типами вместо raw-типов всегда, когда это возможно - то узнаете сразу же, потому что вам покажет ошибку компилятор. Собственно, при правильной настройке он вам и сейчас показывает ошибку - "Вы используете raw-тип". 

В принципе это минорщина всё - мержить так, или поправите сейчас?

2017-10-22 14:40 UTC, zonder129 commented
Поправлю, делов-то)

2017-10-23 10:23 UTC, merged

2017-10-23 10:26 UTC, isopov commented
Ага, а почему этот реквест был в девелоп, а не в мастер, то? Перенес в мастер несколько криво, но что уж теперь.

2017-10-23 10:35 UTC, zonder129 commented
Не знаю, в прошлый раз Богдан нас в девелоп мерджил и вот как-то так и поехало