Ветка для разработки; sandbox-версия стейт-машины
java-park-mail-ru/KVVArtet-09-2017 pull request #4
Opened 2017-09-18 18:49 UTC by KCherkasov

-диаграмма состояний: https://www.lucidchart.com/invitations/accept/d1c33eee-9c3c-42e5-9817-7c3f33c16d8e
-часть кода, реализующая машину состояний (сами конкретные состояния пока без бизнес-логики)
-идея использования стейт-машины - на каждое подключение создавать коннекшн (коннекшны хранятся в ассоциативном контейнере с id сессии в роли ключа), хранящий юзердату, id сессии и экземпляр стейт-машины. Входящие пакеты содержат id сессии и маршрутизируются на соотв. коннекшн. Далее пакет пропускается через стейт-машину в поисках стейта(ов), который(е) знает(ют), как на этот пакет реагировать.
-класс Main - мини-тест корректности реализации стейт-машины (интерфейс Packet выполнен в виде стаба, а конкретные классы стейтов по сути пока тоже стабы)

2017-09-18 22:39 UTC, Badya requested changes

2017-09-18 22:39 UTC, Badya commented on src/main/java/states/AbstractState.java
> +public interface AbstractState {
Обычно, `Abstract` в названии класса явно свидетельствует о том что это абстрактный класс, а не интерфейс - рекомендую поменять имена `State` и `AbstractState` местами

2017-09-18 22:39 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +        System.out.println("push request for state " + stateName + " enqueued");
Использование `System.out/err` не гуд.
Нужно прикрутить логгирование, в случае вопросов - пишите в чат

2017-09-18 23:11 UTC, KCherkasov commented
Имена интерфейса и абстракта поменял, над логгированием с утра поработаю

2017-09-19 07:50 UTC, Badya commented
Не забудьте подтянуть к себе HEAD java-park-mail-ru:develop или сделать rebase

2017-09-19 09:21 UTC, KCherkasov commented
Прикрутил логгер вместо стандартных потоков.

2017-09-19 10:28 UTC, Badya requested changes

2017-09-19 10:28 UTC, Badya commented on src/main/java/states/AbstractState.java
> +  protected static final Logger logger = LoggerFactory.getLogger(AbstractState.class);
Этот логгер будет даже из конечных классов писать как `AbstractState` - будет создавать путаницу, можно заменить на `getClass()`

2017-09-19 10:28 UTC, Badya commented on src/main/java/statemachine/StateStack.java
>      final LinkedList<PendingChange> pendingChanges = new LinkedList<>();
Вместо `LinkedList<E>` в объявлении уместнее было бы наверное сделать `Deque<E>`

2017-09-19 10:28 UTC, Badya commented on src/main/java/states/AbstractState.java
>    private final PendingStack stack;
Поля, даже приватные, лучше располагать вверху

2017-09-19 11:03 UTC, KCherkasov commented on src/main/java/states/AbstractState.java
> +  protected static final Logger logger = LoggerFactory.getLogger(AbstractState.class);
А как именно? Может целесообразнее прикрутить логгер не к абстракту, а к конечным классам тогда? (не понимаю, как использовать нестатический <code>getClass()</code> при инициализации логгера, да и логгер по сути один на всех потомков получается)

2017-09-19 11:38 UTC, KSolovyev commented on src/main/java/states/AbstractState.java
> +  protected static final Logger logger = LoggerFactory.getLogger(AbstractState.class);
Класс используется, как дополнительная метка при логировании. Те он вам напишет [14:59:59] AbstractState.class: blablabla
И будет абсолютно непонятно, откуда это пришло.
getClass() сделать и правда не получится, но не поленитесь, добавьте по логгеру в каждый класс

2017-09-19 11:52 UTC, KSolovyev requested changes

2017-09-19 11:52 UTC, KSolovyev commented on src/main/java/states/StateFactory.java
> +public final class StateFactory {
Идея со стейтами - хорошая, но фабрика должна быть Спринговым сервисом, а не хелпером со статическими методами. Иначе прокидывать зависимости будет очень сложно

2017-09-19 11:52 UTC, KSolovyev commented on src/main/java/Main.java
> +        final PendingStack stack = new StateStack();
это должен быть тест. Можете попробовать сами писать их, unit-тесты пишутся довольно просто

2017-09-19 11:56 UTC, KSolovyev commented
> -идея использования стейт-машины - на каждое подключение создавать коннекшн (коннекшны хранятся в ассоциативном контейнере с id сессии в роли ключа), хранящий юзердату, id сессии и экземпляр стейт-машины. Входящие пакеты содержат id сессии и маршрутизируются на соотв. коннекшн. Далее пакет пропускается через стейт-машину в поисках стейта(ов), который(е) знает(ют), как на этот пакет реагировать.

Обычно у вас есть некоторая иговая сессия, реализующая стейт машину. У нее в каждый конкретный момент есть стейт, ничего искать не надо. Стейт умеет обрабатывать некоторый набор пакетов. Механизм сессий и коннекшнов тоже писать не стоит. В веб-сокетах это есть и заработает из коробки

2017-09-19 13:12 UTC, KCherkasov commented
и планируется сделать (коннекшн - дурное рабочее название, обозначающее класс, объединяющий в себе стейт-машину для конкретного пользователя, его данные (чтобы каждый раз не стучаться в БД, например, активный персонаж с его снаряжением, ид подземелья или группы, к которой принадлежит персонаж (тут надо подумать, как выгоднее), т.е. вещи, которые будут регулярно меняться в течение сессии и которые выгоднее держать в памяти, периодически сохраняя изменения в БД), т.е. по сути продвинутый контроллер, который не только хранит стейт-машину, но и данные, которые нужны часто, но для предотвращения читерства не следует держать только у пользователя (т.е. закешировать, например, ответ про персонажа и его вещи на фронте для ускорения отображения - вполне ок, но валидным будет только хранимое на сервере состояние)

Механизм сессий писать никто и не планировал - идея в том, чтобы использовать ид сессии как ключ для ассоциативного массива описанных выше объектов (назовем их SmartController, т.к. по сути в них инкапсулируются конкретные контроллеры в виде стейтов, плюс функция хранения полезных данных). 
Первой мыслью было использовать как ключ id юзера, но проблема в том, что по факту всякий новый посетитель - неавторизованный юзер, т.е. ключ может быть неуникален. 
Поэтому хочется гарантированно уникальный ключ, как, например id сессии (между id сессии и физическим пользователем вполне однозначная связь, и разлогинивание без дисконнекта не убьет смартконтроллер, а лишь заставит его прочистить юзердату, стек стейт-машины и перевести ее в состояние авторизации).

Идея вытекает из вот такого (вполне вероятно, что не совсем верного) понимания работы сервера - на сервер приходят пакеты с фронта (все валится в один сокет), далее пакет идентифицируется по id сессии и бросается в соотв. смартконтроллер, который его обрабатывает при помощи своей стейт-машины (в результате вполне может поменяться состояние хранимых в смартконтроллере данных и стейт-машины), формирует ответ, который бросает обратно на фронт (все опять через один сокет), а уже фронт разбирается, какому клиенту, какой пакет адресован, и обновляет для них представления.

Т.е. идея с созданием смартконтроллеров - распараллеливание нагрузки (пока реализовать просто как объектный пул, потом можно подумать про многопоточность, например группировать по Х контроллеров в поток),

Но вопрос, насколько это согласуется с идеей REST? Или использовать стейт как контроллер - нормально?

2017-09-19 13:33 UTC, Badya requested changes

2017-09-19 13:33 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +    private final Stack<State> stack = new Stack<>();
`Stack` это по сути уже тоже атавизм - использовать также `Deque` 
JavaDoc:
> A more complete and consistent set of LIFO stack operations is
>  provided by the {@link Deque} interface and its implementations, which
> should be used in preference to this class.

В качестве реализации можно взять `ArrayDeque`

2017-09-19 14:05 UTC, Badya requested changes

2017-09-19 14:05 UTC, Badya commented on src/main/java/states/StateFactory.java
> +public final class StateFactory {
up

2017-09-19 14:05 UTC, Badya commented on src/main/java/Main.java
> +        final PendingStack stack = new StateStack();
up

2017-09-19 14:05 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +        for (PendingChange change : this.pendingChanges) {
Зачем итератор, а потом очистка - из очереди можно вынимать используя `peek()` и `poll()` - таким образом гарантируется очередность и чистить ничего не надо

2017-09-19 14:05 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +            if (!state.update()) {
Что подразумевает апдейт? Почему дальше break?
По стеку итерируемся, но элементы там остаются?

2017-09-19 15:14 UTC, KCherkasov commented on src/main/java/statemachine/StateStack.java
> +            if (!state.update()) {
апдейт - метод для циклически повторяемых действий (привычка с оффлайновых проектов все снабжать методом апдейт). Здесь, например, можно следить за временем с момента последнего запроса от юзера и разлогиниваться по таймауту, перекидывая стейт обратно в ожидание авторизации. И да, элементы остаются (извлекаются они по requestStatePop() или requestStackClear() от другого стейта, т.к. стейт может быть вполне себе долгоживущим (то же нахождение в городе или в подземелье) и логично оставить самому стейту знание про то, когда ему уничтожиться и какие стейты вызвать (по сути эта логика запускается при handlePacket(), например при успешной авторизации стейт, ответственный за нее, кладет в стек pop запрос (на себя) и push запрос на следующий стейт (список персонажей авторизованного игрока).

Про апдейт метод - я бы его пока оставил, окончательно его необходимость будет ясна, когда появится примерный геймплей (потому что стейты города и подземелья будут наиболее нагруженными по функционалу, и вполне возможно, что какая-то циклика там будет, самый простой пример - циклически обновлять состояние карты подземелья (ее сделать разделяемым ресурсом между всеми членами группы) на предмет очередности хода, т.е. дошел ли ход до игрока)

2017-09-19 15:19 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +            if (!state.update()) {
Мы называем это "тик" =)

2017-09-19 15:26 UTC, Badya requested changes

2017-09-19 15:26 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +        private final StackActions action;
Поля тоже наверх

2017-09-19 15:26 UTC, Badya commented on src/main/java/states/AbstractState.java
> +        this.stack.pushState(stateId);
Впринципе писать this на каждый чих не нужно

2017-09-19 15:40 UTC, KCherkasov commented on src/main/java/states/AbstractState.java
> +        this.stack.pushState(stateId);
привычка с плюсов =) 
какой критерий, когда this надо, когда нет (кроме очевидного <code>
class A {
  private SomeType field;

  public void setField(SomeType field) { this.field = field; }
} </code> и в этом духе)?

2017-09-19 15:53 UTC, Badya commented on src/main/java/states/AbstractState.java
> +        this.stack.pushState(stateId);
Обычно this пишут как раз когда есть конфликт имен (как в примере выше), в остальных случаях можно опустить

2017-09-19 16:13 UTC, KCherkasov commented on src/main/java/states/AbstractState.java
> +        this.stack.pushState(stateId);
Ясно, сейчас почищу код

2017-09-19 16:56 UTC, KSolovyev commented
> Идея вытекает из вот такого (вполне вероятно, что не совсем верного) понимания работы сервера - на сервер приходят пакеты с фронта (все валится в один сокет), далее пакет идентифицируется по id сессии и бросается в соотв. смартконтроллер, который его обрабатывает при помощи своей стейт-машины (в результате вполне может поменяться состояние хранимых в смартконтроллере данных и стейт-машины), формирует ответ, который бросает обратно на фронт (все опять через один сокет), а уже фронт разбирается, какому клиенту, какой пакет адресован, и обновляет для них представления.

> Т.е. идея с созданием смартконтроллеров - распараллеливание нагрузки (пока реализовать просто как объектный пул, потом можно подумать про многопоточность, например группировать по Х контроллеров в поток),


> Но вопрос, насколько это согласуется с идеей REST? Или использовать стейт как контроллер - нормально?

Запросы не будем параллельно обрабатывать. Вы этого не умеете и получится с первого раза плохо. Будем параллелить игровые сессии. Если сессий нет и у вас открытый игровой мир, то будем думать, как это лучше сделать. Но принцип будет тот же: запросы игроков, которые могут теоретически конкурировать, будем делать в одном потоке

2017-09-19 17:07 UTC, KCherkasov commented
"Настоящего" открытого мира не планируется.

Есть город, который совмещает в себе функцию лобби (поиск/формирование группы), торговли (набор вендоров, которым можно продать ненужное и что-нибудь купить) и выбора квестов (решено квесты жестко связывать с подземельями, т.е. подземелье генерится под взятое задание, хоть каждый раз и случайно, но необходимые элементы для выполнения квеста там размещаются гарантированно). 

Условно "сессией" можно назвать поход в подземелье, который завершается либо по выходу из него, либо смертью всех персонажей, либо победой над всеми монстрами. В любом из трех случаев группа перемещается обратно в город (в первых двух будет возможность повторить попытку, но подземелье будет сгенерировано по-новой)

2017-09-19 21:29 UTC, KCherkasov commented
Из текущего вроде все заимплементил кроме переделки StateFactory в спринговый сервис

2017-09-19 21:52 UTC, Badya requested changes

2017-09-19 21:52 UTC, Badya commented on src/main/java/statemachine/StateStack.java
> +    public static class StateStackTest {
Тесты распологать в `src/test/java/...` отдельными классами

2017-09-19 21:52 UTC, Badya commented on src/main/java/Main.java
> +        final Result testResult = JUnitCore.runClasses(StateStack.StateStackTest.class);
Запускать тесты нужно через `mvn test`, если они расположены в правильной директории `src/test/java/...`

2017-09-19 22:09 UTC, KCherkasov commented on src/main/java/Main.java
> +        final Result testResult = JUnitCore.runClasses(StateStack.StateStackTest.class);
Понял, этот сделал специально внутренним классом, чтобы поконтролить еще и механизмы методов и состояние полей (выловил пару экземпляров багла пока тестил).

Сейчас переделаю в нормальный тест (придется добавить малость геттеров в StateStack для сбора информации)

2017-09-19 22:30 UTC, KSolovyev commented
Вы же помните, что нужно сделать API? =)
И еще просьба, поправьте соседний пулл реквест

2017-09-19 23:06 UTC, KCherkasov commented
Да, конечно =) 

Как раз коллега и занимается работой над контроллерами, пока я со стейт машиной разбираюсь =)

2017-09-20 08:36 UTC, Badya requested changes

2017-09-20 08:36 UTC, Badya commented on src/main/java/Main.java
> +    public static void main(String[] args) {
Метод мейн вам вообще не нужен как и класс - его просто быть не должно - у вас есть спринг и тесты=)

2017-09-20 08:36 UTC, Badya commented on src/test/java/StateStackTest.java
> +    private static final Logger TEST_LOGGER = LoggerFactory.getLogger(StateStackTest.class);
Логирование в тестах можно опустить

2017-09-20 08:36 UTC, Badya commented on src/test/java/StateStackTest.java
> +    public static void main(String[] args) {
Мейн не нужен если запускать через `mvn test`

2017-09-20 08:36 UTC, Badya commented on src/test/java/StateStackTest.java
> +        stack.clearState();
Вот это повторяется от теста к тесту - хотя перед каждым тестом в `@Before` вы создаете новый стек.
Можно ничего не чистить или вынести это в `@After`

2017-09-20 15:23 UTC, KCherkasov commented on src/main/java/Main.java
> +    public static void main(String[] args) {
касаемо класса мейн - таки нужен, без него тревис не пропускает тест =)

2017-09-20 15:29 UTC, KCherkasov commented
по поводу превращения StateFactory в спринговый сервис - не совсем понял идею, в чем плюсы, если она занимается по сути только разными pojo? Разве зависимости этих pojo должны волновать фабрику?

2017-09-20 16:10 UTC, merged

2017-09-20 16:45 UTC, KSolovyev commented
ну а как вы будете сообщения пользователям отправлять?