Игровая механика
java-park-mail-ru/KVVArtet-09-2017 pull request #49
Opened 2017-12-20 10:39 UTC by KCherkasov

игровая механика:
  - лобби + матчмейкинг
  - процедурно генерируемые подземелья (PvE и PvP режимы)
  - монстры + ИИ
  - фасадный класс игрового мира

ресурсная система:
  - классы персонажей, перки, ветки перков
  - роли монстров
  - процедурная генерация монстров
  - процедурная генерация предметов
  - тесты на ресурсную систему (поднятие фабрик / ассет холдеров + отдача ресурсов/PCG)

вебсокеты:
  - смарт-контроллер (обертка над сокетом + кеш для привязанного юзера)
  - Object pool для смарт-контроллеров
  - сообщения

состояния:
   - распределение хендлеров по различным состояниям игры
   - стейт-машина переработана в сервис

2017-12-20 11:56 UTC, KSolovyev commented
![image](https://user-images.githubusercontent.com/4122313/34206019-ce713a80-e595-11e7-921a-dd6676accc98.png)
![image](https://user-images.githubusercontent.com/4122313/34206031-d9a8ff5a-e595-11e7-82e2-40bb4e36ec08.png)
![image](https://user-images.githubusercontent.com/4122313/34206039-e16204e4-e595-11e7-9b9b-87411c0bb962.png)
😨 😨 😨

2017-12-20 12:03 UTC, KCherkasov commented
Ну процентов 10-15 это ресурсы + разносортные держалки констант (конфиг-плана либо индексы пропертей и т.п.)

По объему добавлений - примерно треть - ресурсные файлы (особо itemParts.json)

2017-12-20 19:33 UTC, KSolovyev commented
можно ссылку на фронт в описание пул реквеста?

2017-12-20 19:58 UTC, KCherkasov commented
добавил ссылку, правда там сейчас могут активно вноситься правки)

2017-12-20 20:13 UTC, KSolovyev commented
а мультиплеер-то успеете к защите? Я сейчас не смог поиграть))

2017-12-20 20:21 UTC, KCherkasov commented
ну бэк готов, сейчас фронтендеры работают над наладкой месседжей на своем конце

2017-12-20 20:27 UTC, KCherkasov commented
бэк умеет матчмейкинг 4 типов: 
- PvE где вся группа состоит из персонажей 1 юзера (по сути TBS против ИИ),
- PvE где каждым персонажем управляет разный пользователь 
- PvP где противостоящими отрядами командуют 2 игрока (т.е. как первый мод PvE, только вместо монстров такая же группа другого игрока)
- PvP где все персонажи в отрядах принадлежат разным пользователям

(наш изначальный концепт включал только 2й и 4й моды, но на плейтесте народ потребовал добавить TBS-мод, добавили, благо для механики особой разницы нет, только в лобби разные очереди на разные моды (ну на 1й мод очереди по факту нет, сразу генерим инстанс и запускаем группу))

2017-12-20 22:22 UTC, KSolovyev requested changes
хочется тестов. Сам-то код хорошо написан. Но он уже достиг того уровня сложности, когда глазами ничего не видно. Нужно хотя бы парочку основных кейсов. Ну и фронт ждем.
Сингл на раздеплоенной версии через сервер работает?

2017-12-20 22:25 UTC, KCherkasov commented
тесты делаем) пока можно посмотреть ресурсную систему (AssetSerializationTest в тестах, пакет project.gamemechanics.resources в коде), ее покрыл тестами целиком, подъем отдача по запросу, генерация монстров и вещей в фабрике

На какие аспекты тесты в первую очередь сделать?

2017-12-20 22:30 UTC, KSolovyev commented
нужны функциональные тесты покрывающие главные игровые сценарии. Все игроки заходят, все готовы, начался бой. Круто, если можно сделать упрощенную партию аля воин против скелета на карте 4х4. Тогда воин делает ход, удар, здоровье отнимается, скелет склеивает ласты, выдается лут. 

Если упростить нельзя, тогда надо подхачить механику и эти кейсы отдельно тестировать.
ход игрока, смерть персонажа, выдача лута и т.д.

2017-12-20 22:43 UTC, KCherkasov commented
понял
упрощения реализуемы, карта создается генератором в любой конфигурации)
бой можно как ИИ против ИИ поднять, так и эмулировать игрока, выдачу лута/экспы/голда по внутренним логам (которые нужны еще и для отдачи на фронт) можно отследить.

элемент лога - ActionResult и его имплементация (пакет project.gamemechanics.battlefield.actionresults) - аналог транзакции в бд - есть информация про инициатора, цель (может отсутствовать) и используемую абилку (тоже может не быть), и дальше перечень вызванных эвентов по шагам(элементарные изменения состояния боя, которые на фронтенде сейчас учатся парсить в отображение - например аое абилка в лист эвентов положит произошедшее на всех атакованных клетках).

Battlefield дополнительно парсит ActionResult'ы и подкладывает туда другие эвенты (например, если от атаки монстр умер, подкладывается цепочка эвентов вознаграждения (юзерам выдается золото и экспа), плюс даются "звездочки на фюзеляж" - меняется статистика (сейчас умеем собирать число побед в пвп/пве раздельно, число фрагов (лично убитых врагов) и ассистов (убитых при участии персонажа товарищем по группе) по пвп/пве отдельно, ну и плюс собираем суммарно нафармленное золото в статистику)

2017-12-21 01:22 UTC, KCherkasov commented
Подлил немного тестов, тест боевки напишу завтра (точнее уже сегодня) днем

2017-12-21 13:49 UTC, KSolovyev commented
Приходите на РК

2017-12-22 21:18 UTC, KSolovyev approved these changes

2017-12-22 21:19 UTC, merged